name: syntax
on: push
jobs:
   linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Compileaza prime
         run: gcc prim.c -o prim
       - name: Testeaza prime
         run: |
          ./ prim 3
          ./ prim 1
          ./ prim 10
